# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Indidé
email: maria@indide.se
description: Unika handgjorda smycken
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/logga-bw.png

# Social settings
facebook_URL: https://www.facebook.com/indide.se
instagram_username: indide_se
tradera: https://www.tradera.com/profile/items/5416174/mariacarolinag?categoryId=36

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes

collections:
  categories:
    output: true
    order:
      - bracelets.md
      - earings.md
      - neckless.md
      - rings.md
      - other.md
  earings:
    output: true
  bracelets:
    output: true